In [65]:
import pandas as pd
import os
import glob
import re
import numpy as np
#loading the data
df = pd.read_csv('../data/translated_questions.csv')
#making spørgsmålsid into integers if they are not NaN
df['answer_id'] = df['answer_id'].astype('Int64')
df.head()

,id,typeid,kategoriid,statusid,offentlighedskode,titel,dato,modtagelsesdato,frigivelsesdato,paragraf,paragrafnummer,spørgsmålsordlyd,spørgsmålstitel,spørgsmålsid,procedurenummer,grundnotatstatus,dagsordenudgavenummer,opdateringsdato,answer_id,translated_questions
0,2,16,14,1,O,"Er ministeren enig i vurderingen af, at grønla...",2014-01-02T00:00:00,NaN,2014-01-02T11:36:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:34.047,3,Does the minister agree with the assessment th...
1,4,16,14,1,O,"Hvad agter ministeren at foretage sig, så kost...",2014-01-02T00:00:00,NaN,2014-01-20T10:12:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:32.563,5,What does the minister intend to do so that bo...
2,16,16,14,1,O,"Mener ministeren, at det er fair, at det offen...",2014-01-03T00:00:00,NaN,2014-01-20T10:14:03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:15.453,19,Does the minister think that it is fair that t...
3,18,16,14,1,O,"Mener ministeren, at det vil være en god ide a...",2014-01-03T00:00:00,NaN,2014-01-20T10:13:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:30.75,17,Does the minister think that it would be a goo...
4,31,16,14,1,O,"Vil udenrigsministeren i lyset af, at danske m...",2014-01-03T00:00:00,NaN,2014-01-03T13:53:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:26.343,62,In light of the fact that the Danish media hav...

In [10]:
#I find all the numbers of the reworded questions in the folder
reworded_questions = glob.glob('../data/questions_rephrased/*.txt')
reworded_questions = [os.path.basename(x) for x in reworded_questions]
reworded_questions = [re.sub(r'\.txt', '', x) for x in reworded_questions]
reworded_questions = [int(x) for x in reworded_questions]

#I find all the numbers of the translated answers in the folder
translated_answers = glob.glob('../data/translated/*.txt')
translated_answers = [os.path.basename(x) for x in translated_answers]
translated_answers = [re.sub(r'\.txt', '', x) for x in translated_answers]
translated_answers = [int(x) for x in translated_answers]

7590

In [19]:
num_reworded = len(reworded_questions)

#There are 3274 reworded questions
#I take the first 3274 questions that are not NaN in the df and find their answer_id

first_3274 = df['answer_id'].head(num_reworded).tolist()

In [22]:
first_3274.sort()
first_3274

TypeError: boolean value of NA is ambiguous

In [23]:
df = pd.read_csv('../data/translated_questions.csv')


files = glob.glob('../data/translated/*.txt')
files = [os.path.basename(x) for x in files]
answer_ids = [re.sub(r'\.txt', '', x) for x in files]
answer_ids = [x for x in answer_ids if not x.endswith('.tmp')]
answer_ids = [int(x) for x in answer_ids]
mask = df['answer_id'].isin(answer_ids)



examples = df[mask]['translated_questions'].tolist()
answer_ids = df[mask]['answer_id'].tolist()

In [34]:
test= zip(examples, answer_ids)
count= 0
ids = []
for example, answer_id in test:
    ids.append(int(answer_id))

In [43]:
#take first 3274 ids
ids = ids[:3274]
ids

[3,
 5,
 17,
 19,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 62,
 65,
 120,
 122,
 124,
 126,
 128,
 134,
 141,
 143,
 149,
 154,
 156,
 158,
 160,
 173,
 175,
 177,
 179,
 188,
 190,
 204,
 206,
 208,
 210,
 213,
 217,
 219,
 223,
 225,
 242,
 244,
 246,
 248,
 250,
 253,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 273,
 275,
 279,
 281,
 283,
 285,
 288,
 290,
 303,
 305,
 333,
 335,
 337,
 350,
 353,
 355,
 360,
 362,
 375,
 377,
 379,
 381,
 383,
 385,
 390,
 392,
 394,
 396,
 398,
 401,
 403,
 405,
 413,
 415,
 417,
 421,
 423,
 425,
 427,
 432,
 435,
 438,
 440,
 442,
 444,
 446,
 448,
 451,
 453,
 474,
 476,
 478,
 481,
 483,
 500,
 504,
 507,
 511,
 515,
 524,
 529,
 534,
 536,
 554,
 556,
 558,
 611,
 613,
 617,
 619,
 621,
 623,
 625,
 627,
 629,
 631,
 633,
 635,
 637,
 652,
 656,
 658,
 660,
 662,
 664,
 666,
 668,
 670,
 672,
 674,
 676,
 678,
 683,
 687,
 689,
 693,
 695,
 697,
 703,
 705,
 707,
 709,
 711,
 716,
 718,
 720,
 723,
 728,
 730,
 732,
 734,
 739,
 741,
 743,
 745,
 754,
 765,
 767,
 769,
 771,
 773,
 775,
 777,
 779,
 781,
 784,
 788,
 790,
 792,
 794,
 796,
 798,
 800,
 802,
 811,
 813,
 815,
 817,
 819,
 821,
 823,
 841,
 876,
 878,
 880,
 884,
 888,
 890,
 892,
 894,
 896,
 898,
 900,
 915,
 917,
 919,
 921,
 923,
 925,
 927,
 929,
 931,
 933,
 935,
 937,
 939,
 943,
 945,
 947,
 949,
 951,
 953,
 955,
 957,
 959,
 961,
 963,
 965,
 968,
 970,
 972,
 974,
 978,
 980,
 982,
 984,
 986,
 990,
 992,
 994,
 996,
 998,
 1013,
 1015,
 1017,
 1019,
 1021,
 1023,
 1028,
 1032,
 1034,
 1036,
 1038,
 1040,
 1042,
 1044,
 1046,
 1048,
 1056,
 1058,
 1060,
 1062,
 1066,
 1071,
 1073,
 1075,
 1078,
 1081,
 1083,
 1087,
 1089,
 1091,
 1093,
 1095,
 1097,
 1101,
 1103,
 1105,
 1107,
 1111,
 1113,
 1115,
 1124,
 1126,
 1128,
 1130,
 1133,
 1135,
 1137,
 1139,
 1141,
 1143,
 1145,
 1147,
 1149,
 1151,
 1153,
 1155,
 1157,
 1159,
 1162,
 1164,
 1166,
 1168,
 1170,
 1174,
 1178,
 1180,
 1182,
 1184,
 1193,
 1196,
 1198,
 1200,
 1204,
 1206,
 1208,
 1212,
 1214,
 1216,
 1221,
 1223,
 1225,
 1227,
 1231,
 1235,
 1240,
 1242,
 1244,
 1246,
 1250,
 1252,
 1263,
 1265,
 1267,
 1269,
 1271,
 1273,
 1275,
 1277,
 1279,
 1281,
 1283,
 1290,
 1292,
 1294,
 1296,
 1304,
 1306,
 1308,
 1310,
 1312,
 1315,
 1317,
 1319,
 1321,
 1323,
 1326,
 1329,
 1332,
 1335,
 1338,
 1343,
 1392,
 1394,
 1419,
 1423,
 1425,
 1427,
 1429,
 1433,
 1435,
 1437,
 1439,
 1441,
 1443,
 1446,
 1448,
 1450,
 1452,
 1456,
 1472,
 1474,
 1478,
 1480,
 1482,
 1484,
 1486,
 1488,
 1490,
 1492,
 1494,
 1497,
 1499,
 1501,
 1503,
 1506,
 1508,
 1510,
 1517,
 1525,
 1545,
 1554,
 1556,
 1558,
 1560,
 1562,
 1570,
 1572,
 1574,
 1576,
 1578,
 1580,
 1582,
 1584,
 1587,
 1589,
 1591,
 1593,
 1595,
 1597,
 1599,
 1601,
 1603,
 1605,
 1607,
 1609,
 1611,
 1613,
 1615,
 1617,
 1619,
 1621,
 1623,
 1625,
 1627,
 1629,
 1631,
 1633,
 1635,
 1637,
 1639,
 1641,
 1643,
 1645,
 1647,
 1649,
 1651,
 1653,
 1655,
 1657,
 1660,
 1662,
 1664,
 1666,
 1668,
 1670,
 1672,
 1674,
 1678,
 1683,
 1699,
 1701,
 1703,
 1705,
 1707,
 1711,
 1713,
 1726,
 1729,
 1740,
 1742,
 1744,
 1747,
 1749,
 1756,
 1759,
 1761,
 1765,
 1767,
 1771,
 1773,
 1781,
 1783,
 1786,
 1788,
 1792,
 1794,
 1796,
 1798,
 1800,
 1802,
 1805,
 1812,
 1825,
 1827,
 1829,
 1831,
 1833,
 1835,
 1837,
 1840,
 1842,
 1844,
 1846,
 1852,
 1854,
 1856,
 1858,
 1860,
 1862,
 1864,
 1868,
 1874,
 1876,
 1878,
 1880,
 1886,
 1892,
 1894,
 1896,
 1898,
 1910,
 1920,
 1922,
 1924,
 1926,
 1928,
 1930,
 1932,
 1934,
 1936,
 1938,
 1940,
 1954,
 1956,
 1958,
 1960,
 1962,
 1964,
 1966,
 1970,
 1972,
 1974,
 1976,
 1978,
 1983,
 1985,
 1987,
 1992,
 1996,
 1998,
 2000,
 2002,
 2004,
 2006,
 2008,
 2012,
 2014,
 2016,
 2018,
 2020,
 2022,
 2024,
 2026,
 2032,
 2037,
 2039,
 2041,
 2052,
 2054,
 2056,
 2058,
 2060,
 2069,
 2076,
 2078,
 2082,
 2086,
 2089,
 2091,
 2093,
 2095,
 2097,
 2103,
 2107,
 2110,
 2112,
 2114,
 2131,
 2133,
 2135,
 2137,
 2142,
 2144,
 2161,
 2183,
 2185,
 2187,
 2189,
 2207,
 2209,
 2211,
 2213,
 2215,
 2217,
 2219,
 2221,
 2223,
 2225,
 2236,
 2247,
 2249,
 2257,
 2259,
 2261,
 2264,
 2266,
 2271,
 2273,
 2275,
 2279,
 2281,
 2283,
 2285,
 2287,
 2289,
 2291,
 2301,
 2361,
 2363,
 2365,
 2399,
 2401,
 2414,
 2416,
 2418,
 2420,
 2422,
 2424,
 2428,
 2439,
 2446,
 2451,
 2456,
 2460,
 2462,
 2464,
 2466,
 2471,
 2473,
 2475,
 2477,
 2479,
 2481,
 2483,
 2485,
 2487,
 2489,
 2511,
 2513,
 2521,
 2523,
 2525,
 2531,
 2533,
 2535,
 2537,
 2539,
 2541,
 2543,
 2547,
 2549,
 2551,
 2553,
 2555,
 2557,
 2559,
 2561,
 2563,
 2565,
 2571,
 2577,
 2579,
 2581,
 2583,
 2585,
 2587,
 2589,
 2591,
 2593,
 2595,
 2597,
 2599,
 2604,
 2611,
 2613,
 2619,
 2621,
 2623,
 2635,
 2637,
 2639,
 2641,
 2643,
 2645,
 2647,
 2649,
 2654,
 2656,
 2660,
 2662,
 2664,
 2666,
 2668,
 2670,
 2672,
 2680,
 2683,
 2686,
 2688,
 2690,
 2692,
 2694,
 2696,
 2698,
 2700,
 2702,
 2704,
 2706,
 2708,
 2710,
 2712,
 2714,
 2716,
 2718,
 2720,
 2722,
 2724,
 2726,
 2734,
 2736,
 2740,
 2742,
 2744,
 2746,
 2748,
 2763,
 2765,
 2767,
 2771,
 2775,
 2777,
 2779,
 2781,
 2787,
 5705,
 7512,
 7514,
 7516,
 7518,
 7520,
 7522,
 7524,
 7526,
 7528,
 7530,
 7532,
 7534,
 7536,
 7538,
 7540,
 7542,
 7544,
 7546,
 7548,
 7550,
 7552,
 7554,
 7556,
 7558,
 7560,
 7562,
 7564,
 7566,
 7572,
 7574,
 7576,
 7578,
 7580,
 7582,
 7584,
 7586,
 7588,
 7590,
 7602,
 7604,
 7609,
 7611,
 7613,
 7615,
 7617,
 7619,
 7621,
 7623,
 7625,
 7627,
 7629,
 7631,
 7633,
 7637,
 7641,
 7647,
 7649,
 7655,
 7657,
 7659,
 7661,
 10162,
 10214,
 10411,
 10414,
 10418,
 10421,
 10426,
 10427,
 10430,
 10431,
 10435,
 10436,
 10437,
 10440,
 10441,
 14381,
 21854,
 21868,
 21877,
 25505,
 26061,
 26062,
 27401,
 88813,
 89165,
 89171,
 89173,
 89177,
 89179,
 89184,
 89214,
 89228,
 89251,
 89263,
 89265,
 105760,
 105762,
 105792,
 105815,
 105891,
 105893,
 108291,
 108949,
 109414,
 109415,
 109416,
 109418,
 109421,
 109422,
 110254,
 110255,
 110481,
 110951,
 110962,
 110964,
 111003,
 153277,
 256770,
 256937,
 256962,
 256994,
 257670,
 268361,
 271022,
 271594,
 271603,
 271699,
 271700,
 271702,
 271757,
 271797,
 272162,
 272651,
 273111,
 273363,
 273364,
 273507,
 276372,
 278210,
 278211,
 278216,
 279072,
 279715,
 281392,
 281933,
 282019,
 282556,
 282806,
 283063,
 284225,
 284226,
 284227,
 284228,
 284229,
 284231,
 284286,
 284680,
 285584,
 285717,
 285730,
 286395,
 287537,
 287547,
 287747,
 288000,
 288023,
 288786,
 289148,
 289150,
 290447,
 290677,
 291737,
 291855,
 292259,
 292263,
 292265,
 292380,
 292381,
 292383,
 292437,
 292439,
 292457,
 292458,
 292784,
 293746,
 295204,
 295566,
 296849,
 296873,
 297927,
 298269,
 299158,
 299159,
 300395,
 300415,
 300422,
 300468,
 300704,
 300792,
 300800,
 300804,
 300955,
 302586,
 303003,
 303321,
 303322,
 303456,
 303481,
 303955,
 304353,
 304355,
 304366,
 304386,
 304824,
 304886,
 304987,
 305177,
 305362,
 305365,
 305450,
 305622,
 305760,
 305832,
 305909,
 305917,
 306082,
 306159,
 306872,
 306874,
 307062,
 307377,
 307402,
 307503,
 307505,
 307508,
 307547,
 307548,
 ...]

In [42]:
ids.sort()
ids[-10:] #this looks good

[726608,
 726731,
 726924,
 727585,
 728234,
 728235,
 728374,
 728585,
 731920,
 732053]

In [47]:
#i take the first 3274 ids of the translated questions that are not NaN

translated_ids = df['answer_id'].dropna().head(3274).tolist()

In [48]:
#now I want to check how many of these ids are among the translated answers
among = []
for id in translated_ids:
    if id in translated_answers:
        among.append(id)

In [49]:
len(among)
#Im just going to ignore these for now and maybe compare later

838

Moving on to figuring out what the correct answer_ids are for a question with a given answer link

In [80]:
#loading new df
correct_df = pd.read_csv('../data/raw/questions_with_links_new.csv')
correct_df.head()

,id,typeid,kategoriid,statusid,offentlighedskode,titel,dato,modtagelsesdato,frigivelsesdato,paragraf,paragrafnummer,spørgsmålsordlyd,spørgsmålstitel,spørgsmålsid,procedurenummer,grundnotatstatus,dagsordenudgavenummer,opdateringsdato,answer_id,filurl
0,2,16,14,1,O,"Er ministeren enig i vurderingen af, at grønla...",2014-01-02T00:00:00,NaN,2014-01-02T11:36:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:34.047,3,https://www.ft.dk/samling/20131/spoergsmaal/S7...
1,4,16,14,1,O,"Hvad agter ministeren at foretage sig, så kost...",2014-01-02T00:00:00,NaN,2014-01-20T10:12:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:32.563,5,https://www.ft.dk/samling/20131/spoergsmaal/S7...
2,16,16,14,1,O,"Mener ministeren, at det er fair, at det offen...",2014-01-03T00:00:00,NaN,2014-01-20T10:14:03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:15.453,19,https://www.ft.dk/samling/20131/spoergsmaal/S7...
3,18,16,14,1,O,"Mener ministeren, at det vil være en god ide a...",2014-01-03T00:00:00,NaN,2014-01-20T10:13:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:30.75,17,https://www.ft.dk/samling/20131/spoergsmaal/S7...
4,31,16,14,1,O,"Vil udenrigsministeren i lyset af, at danske m...",2014-01-03T00:00:00,NaN,2014-01-03T13:53:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-05-29T11:11:26.343,62,https://www.ft.dk/samling/20131/spoergsmaal/S7...

In [81]:
incorrect_df = pd.read_csv('../data/raw/questions_with_filurls.csv')
incorrect_df['answer_id'] = incorrect_df['answer_id'].fillna(-1).astype('Int64')
incorrect_df[5000:5010]

,id,typeid,kategoriid,statusid,offentlighedskode,titel,dato,modtagelsesdato,frigivelsesdato,paragraf,paragrafnummer,spørgsmålsordlyd,spørgsmålstitel,spørgsmålsid,procedurenummer,grundnotatstatus,dagsordenudgavenummer,opdateringsdato,answer_id,filurl
5000,111924,16,14,1,O,"Hvad er ministerens holdning til, at et stort ...",2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:18:26.657,111929,[]
5001,111926,16,14,1,O,"Har ministeren forståelse for, at Silkeborg Ko...",2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:18:28.093,111931,[]
5002,111928,16,14,1,O,"Hvad mener ministeren, man kan gøre for at for...",2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:11:35.62,111935,NaN
5003,111930,16,14,1,O,"Mener ministeren, at det kan udelukkes, at Sil...",2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:18:27.357,111933,[]
5004,111932,16,14,1,O,Vil ministeren være med til at indkalde alle ø...,2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:11:35.433,111937,[]
5005,111934,16,14,1,O,Vil ministeren være med til at se på mulighede...,2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:11:35.857,111939,[]
5006,111936,16,14,1,O,Hvilke konsekvenser mener ministeren det vil h...,2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:13:56.403,111941,NaN
5007,111938,16,14,1,O,"Har ministeren en holdning til, hvem man som f...",2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:11:08.807,111952,[]
5008,111940,16,14,1,O,Vil ministeren uddybe og dokumentere sin påsta...,2011-10-13T00:00:00,2011-10-13T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:11:33.62,111950,[]
5009,111949,16,14,1,O,"Finder ministeren det hensigtsmæssigt, at pass...",2011-10-14T00:00:00,2011-10-14T00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-06T03:11:36.713,111954,[]

In [63]:
def match_answer_id(x):
    if isinstance(x, list) and len(x) > 0:
        try:
            match = correct_df.loc[correct_df['filurl'] == x[0]]['answer_id'].iloc[0]
            return match
        except IndexError:
            try:
                match = correct_df.loc[correct_df['filurl'] == x[1]]['answer_id'].iloc[0]
                return match
            except IndexError:
                return None
    else:
        return None

incorrect_df['correct_answer_id'] = incorrect_df['filurl'].apply(match_answer_id)
merged_df = incorrect_df.merge(correct_df[['filurl', 'answer_id']], on='filurl', how='left')

MemoryError: Unable to allocate 16.0 GiB for an array with shape (4, 535426576) and data type int64

In [66]:
answer_id_map = correct_df.set_index('filurl')['answer_id'].to_dict()

def match_answer_id(x):
    if isinstance(x, list) and len(x) > 0:
        x = x[0]
    return answer_id_map.get(x, np.nan)

incorrect_df['correct_answer_id'] = incorrect_df['filurl'].apply(match_answer_id)

In [74]:
import ast

In [73]:
incorrect_df['filurl'][0]

"['https://www.ft.dk/samling/20131/spoergsmaal/S731/svar/1102093/1319919.pdf']"

In [71]:
correct_df['filurl'][0]

'https://www.ft.dk/samling/20131/spoergsmaal/S725/svar/1102491/1320529.pdf'

In [82]:
import ast

correct_df['filurl'] = correct_df['filurl'].str.strip().str.lower().astype(str)
answer_id_map = correct_df.set_index('filurl')['answer_id'].to_dict()

def match_answer_id(x):
    if isinstance(x, list) and len(x) > 0:
        x = str(x[0]).strip().lower()
    return answer_id_map.get(x, np.nan)

incorrect_df['filurl'] = incorrect_df['filurl'].apply(lambda x: [str(x[0]).strip().lower()] if isinstance(x, list) and len(x) > 0 else x)
incorrect_df['correct_answer_id'] = incorrect_df['filurl'].apply(match_answer_id)

In [85]:
correct_df_unique = correct_df['filurl'].unique()
incorrect_df_unique = incorrect_df['filurl'].apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else x).unique()

print("Unique values in correct_df:", len(correct_df_unique))
print("Unique values in incorrect_df:", len(incorrect_df_unique))
print("Unique values in both:", len(correct_df_unique.intersection(incorrect_df_unique)))

Unique values in correct_df: 8176
Unique values in incorrect_df: 7609

AttributeError: 'numpy.ndarray' object has no attribute 'intersection'